### ISSUE TITLE
Breaks when user settings are added

### ISSUE THREAD

**Issue by NathanJang** [lionandoil/SublimeLaTeXWordCount#12]
I followed the advice on the default `.sublime-settings` and put this in my user configuration `LaTeXWordCount.sublime-settings`:

    {
      "LaTeX": {
        "exclude_footnotes": false
      }
    }

Then, when I run the word count, nothing appears to happen. This is printed on the console:

    Traceback (most recent call last):
      File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
        return self.run(edit)
      File "WordCount in /Users/jonchan/Library/Application Support/Sublime Text 3/Installed Packages/LaTeX Word Count.sublime-package", line 142, in run
      File "WordCount in /Users/jonchan/Library/Application Support/Sublime Text 3/Installed Packages/LaTeX Word Count.sublime-package", line 89, in wordcount_latex
    TypeError: 'NoneType' object is not iterable

This doesn't happen when the user config file is blank.

**Comment by lionandoil** [comment]
Hmm the current version can't look up default values that are nested in other config elements, so as a workaround for now you could simply copy-paste the entire "LaTeX" configuration block and adjust the exclude-options in there, i.e. have this as your user package settings:

    {
    	"LaTeX": {
    		"markup_commands": ["text\\w+", "uppercase", "uline", "emph", "caption"],
    		"exclude_headers": false,
    		"exclude_footnotes": false,
    		"exclude_appendices": true,
    		"exclude_abstract": false
    	}
    }

Please let me know if that works for you

**Comment by NathanJang** [comment]
It does! Any ideas on how to fix it? I don't know Python, so I can't help.
